2021-04-27 14:19:33,095 INFO    MainThread:14564 [wandb_setup.py:_flush():69] setting env: {}
2021-04-27 14:19:33,095 INFO    MainThread:14564 [wandb_setup.py:_flush():69] setting login settings: {}
2021-04-27 14:19:33,095 INFO    MainThread:14564 [wandb_init.py:_log_setup():336] Logging user logs to /Users/merden/Research/denoiser/wandb/run-20210427_141933-vrq1pf3h/logs/debug.log
2021-04-27 14:19:33,095 INFO    MainThread:14564 [wandb_init.py:_log_setup():337] Logging internal logs to /Users/merden/Research/denoiser/wandb/run-20210427_141933-vrq1pf3h/logs/debug-internal.log
2021-04-27 14:19:33,096 INFO    MainThread:14564 [wandb_init.py:init():369] calling init triggers
2021-04-27 14:19:33,096 INFO    MainThread:14564 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {}
2021-04-27 14:19:33,096 INFO    MainThread:14564 [wandb_init.py:init():418] starting backend
2021-04-27 14:19:33,096 INFO    MainThread:14564 [backend.py:_multiprocessing_setup():69] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2021-04-27 14:19:33,105 INFO    MainThread:14564 [backend.py:ensure_launched():123] starting backend process...
2021-04-27 14:19:33,110 INFO    MainThread:14564 [backend.py:ensure_launched():127] started backend process with pid: 14570
2021-04-27 14:19:33,112 INFO    MainThread:14564 [wandb_init.py:init():423] backend started and connected
2021-04-27 14:19:33,114 INFO    MainThread:14564 [wandb_init.py:init():465] updated telemetry
2021-04-27 14:19:33,115 INFO    MainThread:14564 [wandb_init.py:init():484] communicating current version
2021-04-27 14:19:34,112 INFO    MainThread:14564 [wandb_init.py:init():489] got version response 
2021-04-27 14:19:34,112 INFO    MainThread:14564 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-04-27 14:19:34,271 INFO    MainThread:14564 [wandb_init.py:init():522] starting run threads in backend
2021-04-27 14:19:35,909 INFO    MainThread:14564 [wandb_run.py:_console_start():1524] atexit reg
2021-04-27 14:19:35,910 INFO    MainThread:14564 [wandb_run.py:_redirect():1371] redirect: SettingsConsole.REDIRECT
2021-04-27 14:19:35,910 INFO    MainThread:14564 [wandb_run.py:_redirect():1376] Redirecting console.
2021-04-27 14:19:35,912 INFO    MainThread:14564 [wandb_run.py:_redirect():1438] Redirects installed.
2021-04-27 14:19:35,912 INFO    MainThread:14564 [wandb_init.py:init():546] run started, returning control to user process
2021-04-27 14:19:35,929 INFO    MainThread:14564 [wandb_run.py:_atexit_cleanup():1494] got exitcode: 1
2021-04-27 14:19:35,930 INFO    MainThread:14564 [wandb_run.py:_restore():1466] restore
2021-04-27 14:19:38,077 INFO    MainThread:14564 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 470
  total_bytes: 470
}

2021-04-27 14:19:38,184 INFO    MainThread:14564 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 470
  total_bytes: 470
}

2021-04-27 14:19:38,289 INFO    MainThread:14564 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 470
  total_bytes: 2214
}

2021-04-27 14:19:38,465 INFO    MainThread:14564 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 470
  total_bytes: 2298
}

2021-04-27 14:19:38,571 INFO    MainThread:14564 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 2298
  total_bytes: 2298
}

2021-04-27 14:19:38,675 INFO    MainThread:14564 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 2298
  total_bytes: 2298
}

2021-04-27 14:19:38,782 INFO    MainThread:14564 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 2298
  total_bytes: 2298
}

2021-04-27 14:19:38,888 INFO    MainThread:14564 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 2298
  total_bytes: 2298
}

2021-04-27 14:19:38,993 INFO    MainThread:14564 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 2298
  total_bytes: 2298
}

2021-04-27 14:19:39,095 INFO    MainThread:14564 [wandb_run.py:_wait_for_finish():1616] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 2298
  total_bytes: 2298
}

2021-04-27 14:19:40,201 INFO    MainThread:14564 [wandb_run.py:_show_files():1838] logging synced files
