2021-04-27 14:34:44,347 INFO    MainThread:14790 [wandb_setup.py:_flush():69] setting env: {}
2021-04-27 14:34:44,347 INFO    MainThread:14790 [wandb_setup.py:_flush():69] setting login settings: {}
2021-04-27 14:34:44,348 INFO    MainThread:14790 [wandb_init.py:_log_setup():336] Logging user logs to /Users/merden/Research/denoiser/wandb/run-20210427_143444-1flpl83p/logs/debug.log
2021-04-27 14:34:44,348 INFO    MainThread:14790 [wandb_init.py:_log_setup():337] Logging internal logs to /Users/merden/Research/denoiser/wandb/run-20210427_143444-1flpl83p/logs/debug-internal.log
2021-04-27 14:34:44,348 INFO    MainThread:14790 [wandb_init.py:init():369] calling init triggers
2021-04-27 14:34:44,348 INFO    MainThread:14790 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {}
2021-04-27 14:34:44,348 INFO    MainThread:14790 [wandb_init.py:init():418] starting backend
2021-04-27 14:34:44,348 INFO    MainThread:14790 [backend.py:_multiprocessing_setup():69] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2021-04-27 14:34:44,357 INFO    MainThread:14790 [backend.py:ensure_launched():123] starting backend process...
2021-04-27 14:34:44,363 INFO    MainThread:14790 [backend.py:ensure_launched():127] started backend process with pid: 14796
2021-04-27 14:34:44,366 INFO    MainThread:14790 [wandb_init.py:init():423] backend started and connected
2021-04-27 14:34:44,368 INFO    MainThread:14790 [wandb_init.py:init():465] updated telemetry
2021-04-27 14:34:44,369 INFO    MainThread:14790 [wandb_init.py:init():484] communicating current version
2021-04-27 14:34:45,379 INFO    MainThread:14790 [wandb_init.py:init():489] got version response 
2021-04-27 14:34:45,379 INFO    MainThread:14790 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-04-27 14:34:45,545 INFO    MainThread:14790 [wandb_init.py:init():522] starting run threads in backend
2021-04-27 14:34:46,921 INFO    MainThread:14790 [wandb_run.py:_console_start():1524] atexit reg
2021-04-27 14:34:46,922 INFO    MainThread:14790 [wandb_run.py:_redirect():1371] redirect: SettingsConsole.REDIRECT
2021-04-27 14:34:46,923 INFO    MainThread:14790 [wandb_run.py:_redirect():1376] Redirecting console.
2021-04-27 14:34:46,924 INFO    MainThread:14790 [wandb_run.py:_redirect():1438] Redirects installed.
2021-04-27 14:34:46,925 INFO    MainThread:14790 [wandb_init.py:init():546] run started, returning control to user process
2021-04-27 14:34:46,945 INFO    MainThread:14790 [wandb_run.py:_atexit_cleanup():1494] got exitcode: 1
2021-04-27 14:34:46,945 INFO    MainThread:14790 [wandb_run.py:_restore():1466] restore
2021-04-27 14:34:49,099 INFO    MainThread:14790 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 470
  total_bytes: 470
}

2021-04-27 14:34:49,564 INFO    MainThread:14790 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 470
  total_bytes: 2214
}

2021-04-27 14:34:49,765 INFO    MainThread:14790 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 470
  total_bytes: 2298
}

2021-04-27 14:34:49,870 INFO    MainThread:14790 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 2298
  total_bytes: 2298
}

2021-04-27 14:34:49,972 INFO    MainThread:14790 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 2298
  total_bytes: 2298
}

2021-04-27 14:34:50,077 INFO    MainThread:14790 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 2298
  total_bytes: 2298
}

2021-04-27 14:34:50,179 INFO    MainThread:14790 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 2298
  total_bytes: 2298
}

2021-04-27 14:34:50,281 INFO    MainThread:14790 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 2298
  total_bytes: 2298
}

2021-04-27 14:34:50,383 INFO    MainThread:14790 [wandb_run.py:_wait_for_finish():1616] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 2298
  total_bytes: 2298
}

2021-04-27 14:34:51,474 INFO    MainThread:14790 [wandb_run.py:_show_files():1838] logging synced files
